In [1]:
# Step 0: Import libraries
import mysql.connector
import pandas as pd

# Step 1: Connect to MySQL
conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="bike",
    database="dataspark"
)
cursor = conn.cursor()

In [10]:
#1️ Total Sales by Product
query1 = """
SELECT p.ProductName, SUM(s.Quantity) AS Total_Sales
FROM sales s
JOIN products p ON s.ProductKey = p.ProductKey
GROUP BY p.ProductName;
"""

df_total_sales = pd.read_sql(query1, conn)
df_total_sales.head()  # Shows first 5 rows

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\684035247.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_total_sales = pd.read_sql(query1, conn)

                              ProductName  Total_Sales
0         Contoso Lens Adapter M450 White         49.0
1         A. Datum SLR Camera X136 Silver         49.0
2  Fabrikam Microwave 1.5CuFt X1100 Black         45.0
3          Contoso SLR Camera M146 Orange         69.0
4   Adventure Works Laptop8.9 E0890 White         82.0

In [22]:
#2️ Most Sold Product
query2 = """
SELECT p.ProductName, SUM(s.Quantity) AS Total_Sales
FROM sales s
JOIN products p ON s.ProductKey = p.ProductKey
GROUP BY p.ProductName
ORDER BY Total_Sales DESC
LIMIT 10;
"""

df_most_sold = pd.read_sql(query2, conn)
df_most_sold

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\3137225936.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_most_sold = pd.read_sql(query2, conn)

                                  ProductName  Total_Sales
0              WWI Desktop PC2.33 X2330 Black        550.0
1              WWI Desktop PC1.80 E1800 White        538.0
2  Adventure Works Desktop PC1.60 ED160 Black        521.0
3  Adventure Works Desktop PC2.30 MD230 White        521.0
4  Adventure Works Desktop PC1.80 ED180 Black        520.0
5  Adventure Works Desktop PC2.30 MD230 Black        514.0
6              WWI Desktop PC1.60 E1600 Black        509.0
7             WWI Desktop PC1.60 E1600 Silver        507.0
8  Adventure Works Desktop PC1.60 ED160 White        505.0
9              WWI Desktop PC1.80 E1801 Black        505.0

In [21]:
#3 Total Quantity by Store and Product

query3 = """
SELECT st.StoreKey, p.ProductName, SUM(s.Quantity) AS Total_Quantity
FROM sales s
JOIN products p ON s.ProductKey = p.ProductKey
JOIN store st ON s.StoreKey = st.StoreKey
GROUP BY st.StoreKey, p.ProductName;
"""

df_quantity_store_product = pd.read_sql(query3, conn)
df_quantity_store_product

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\2094067238.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_quantity_store_product = pd.read_sql(query3, conn)

,StoreKey,ProductName,Total_Quantity
0,0,A. Datum Advanced Digital Camera M300 Azure,4.0
1,0,A. Datum Advanced Digital Camera M300 Black,4.0
2,0,A. Datum Advanced Digital Camera M300 Green,3.0
3,0,A. Datum Advanced Digital Camera M300 Grey,10.0
4,0,A. Datum Advanced Digital Camera M300 Orange,10.0
...,...,...,...
35747,66,WWI Wireless Bluetooth Stereo Headphones M270 ...,2.0
35748,66,WWI Wireless Transmitter and Bluetooth Headpho...,7.0
35749,66,WWI Wireless Transmitter and Bluetooth Headpho...,3.0
35750,66,WWI Wireless Transmitter and Bluetooth Headpho...,3.0
35751,66,WWI Wireless Transmitter and Bluetooth Headpho...,1.0

In [13]:
#4️ Exchange Rate for Specific Date
query4 = """
SELECT Exchange
FROM exchange_rates
WHERE Date = '1/1/2015' AND Currency = 'EUR';
"""

df_exchange_rate = pd.read_sql(query4, conn)
df_exchange_rate

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\451152740.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_exchange_rate = pd.read_sql(query4, conn)

  Exchange
0   0.8237

In [14]:
#5️ Average Order quantity sold Size by Store
query5 = """
SELECT st.StoreKey, AVG(s.Quantity) AS Average_Order_Size
FROM sales s
JOIN store st ON s.StoreKey = st.StoreKey
GROUP BY st.StoreKey;
"""

df_avg_order_size = pd.read_sql(query5, conn)
df_avg_order_size.head()

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\1514801012.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_avg_order_size = pd.read_sql(query5, conn)

   StoreKey  Average_Order_Size
0        10              3.0804
1         0              3.1379
2        38              3.1673
3        33              3.1606
4        43              3.1776

In [15]:
#6️Total Sales by Currency
query6 = """
SELECT s.CurrencyCode, SUM(s.Quantity) AS Total_Sales
FROM sales s
GROUP BY s.CurrencyCode;
"""

df_sales_currency = pd.read_sql(query6, conn)
df_sales_currency

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\1064439085.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sales_currency = pd.read_sql(query6, conn)

  CurrencyCode  Total_Sales
0          CAD      16793.0
1          USD     106407.0
2          GBP      25298.0
3          EUR      40050.0
4          AUD       9209.0

In [16]:
# 7 Sales for Specific Product by Year
query7 = """
SELECT EXTRACT(YEAR FROM s.OrderDate) AS Year, SUM(s.Quantity) AS Total_Sales
FROM sales s
JOIN products p ON s.ProductKey = p.ProductKey
WHERE p.ProductName = 'Contoso 512MB MP3 Player E51 Silver'
GROUP BY Year;
"""

df_sales_year = pd.read_sql(query7, conn)
df_sales_year

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\796944822.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sales_year = pd.read_sql(query7, conn)

   Year  Total_Sales
0  2016          2.0
1  2017         13.0
2  2018         32.0
3  2019         12.0
4  2020          6.0

In [17]:
#8️ Total Quantity Sold per Month
query8 = """
SELECT EXTRACT(MONTH FROM s.OrderDate) AS Month, SUM(s.Quantity) AS Total_Quantity
FROM sales s
GROUP BY Month;
"""

df_quantity_month = pd.read_sql(query8, conn)
df_quantity_month

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\1690323544.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_quantity_month = pd.read_sql(query8, conn)

    Month  Total_Quantity
0       1         24018.0
1       2         26911.0
2       3          8876.0
3       4          2001.0
4       5         16525.0
5       6         15538.0
6       7         13925.0
7       8         14751.0
8       9         15688.0
9      10         16258.0
10     11         16152.0
11     12         27114.0

In [23]:
# 9 Customers Who Purchased in More Than 5 Stores
query9 = """
SELECT c.Name, COUNT(DISTINCT s.StoreKey) AS Store_Count
FROM sales s
JOIN customer c ON s.CustomerKey = c.CustomerKey
GROUP BY c.Name
HAVING COUNT(DISTINCT s.StoreKey) > 5;
"""

df_customers_5stores = pd.read_sql(query9, conn)
df_customers_5stores.head()

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\1607456084.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_customers_5stores = pd.read_sql(query9, conn)

           Name  Store_Count
0  Aaron Hughes            6
1     Adam Cook            6
2      Al James            6
3   Amos Carter            6
4  Anna Collard            6

In [19]:
#10 Products Not Sold
query10 = """
SELECT p.ProductName
FROM products p
LEFT JOIN sales s ON p.ProductKey = s.ProductKey
WHERE s.OrderNumber IS NULL;
"""

df_products_not_sold = pd.read_sql(query10, conn)
df_products_not_sold.head()

C:\Users\dhars\AppData\Local\Temp\ipykernel_3324\4060209563.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_products_not_sold = pd.read_sql(query10, conn)

                                         ProductName
0  Contoso Home Theater System 5.1 Channel M1530 ...
1             Contoso Washer & Dryer 21in E210 Green
2             Adventure Works Floor Lamp X1150 Black
3             Adventure Works Floor Lamp M2150 Black
4             Adventure Works Chandelier M6150 Black